# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  pull_request:
    branches: [ "main", "scenarios/*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B compile --file pom.xml

    - name: Extract test pattern from PR message
      id: extract_test_pattern
      run: |
        PR_BODY="${{ github.event.pull_request.body }}"
        echo "Full PR body:"
        echo "$PR_BODY"

        # Use bash string manipulation to extract the test pattern
        if echo "$PR_BODY" | grep -q -i "Run tests:"; then
          # Extract the line with "Run tests:"
          TEST_LINE=$(echo "$PR_BODY" | grep -i "Run tests:")
          echo "Found line: $TEST_LINE"

          # Extract everything after the colon
          TEST_PATTERN=$(echo "$TEST_LINE" | sed 's/.*[Rr]un tests: *//' | tr -d '\r')
          echo "Has test pattern: $TEST_PATTERN"
          echo "TEST_PATTERN=$TEST_PATTERN" >> $GITHUB_ENV
        else
          echo "No test pattern found in PR message"
        fi

    - name: Run Specific Tests
      if: env.TEST_PATTERN != ''
      run: mvn -B test -Dtest=${{ env.TEST_PATTERN }} --file pom.xml

    - name: Run All Tests
      if: env.TEST_PATTERN == ''
      run: mvn -B test --file pom.xml
